url:
  railstutorial: "https://www.railstutorial.org/"
  railstutorial_book: "https://www.railstutorial.org/book"
  railstutorial_help: "https://www.railstutorial.org/help"
  screencasts: "https://screencasts.railstutorial.org/"
  learnenough: "https://www.learnenough.com/"
  rubyonrails: "https://rubyonrails.org/"
